name: Cypress Tests

on:
  workflow_run:
    workflows: ["Deploy Infrastructure"]  # Name of the workflow you want to wait for
    types:
      - completed

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # This condition checks if the previous workflow ran successfully
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'https://fidelis-resume.fozdigitalz.com/'  # Use the CloudFront URL
          wait-on-timeout: 60  # Set a timeout for the wait-on command
          record: true
          parallel: false  # Run tests in a single instance
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Cypress status
        id: cypress-status
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Cypress tests passed!"
            echo "cypress-status=success" >> $GITHUB_ENV
          else
            echo "Cypress tests failed!"
            echo "cypress-status=failure" >> $GITHUB_ENV
          fi