name: Python Testing with Pytest

on:
  push:
    branches:
      - main  # Run tests when changes are pushed to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the runner

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt  # Install dependencies from requirements-test.txt

    - name: Run tests with pytest
      run: |
        pytest tests/test_lambda.py  # Run the test script you provided